version: '3'

services:
  backend:
    build: ./backend
    environment:
      - PGUSER=matcha
      - PGHOST=postgres
      - PGPASSWORD=Matcha12345
      - PGDATABASE=matchadb
      - PGPORT=5432
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
  proxy:
    build: ./proxy
    ports:
      - '8080:8080'
    links:
      - frontend:frontend
      - backend:backend
  postgres:
    image: postgres:12.1
    environment:
      - POSTGRES_USER=matcha
      - POSTGRES_PASSWORD=Matcha12345
      - POSTGRES_DB=matchadb
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
volumes:
  pgdata:
