version: '3'

services:
  backend:
    build: ./backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
  proxy:
    build: ./proxy
    ports:
      - '8080:8080'
    links:
      - frontend:frontend
      - backend:backend
